spring:
  datasource:
    url: jdbc:oracle:thin:@karinasstyles_medium?TNS_ADMIN=Wallet_KarinasStyles
    username: DEVELOPER_01
    password: Admin12345678
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        # FORZAR NOMBRES EN MAYÚSCULAS
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  main:
    allow-bean-definition-overriding: true