-- CREACIÓN DE TABLAS

CREATE TABLE buys (
    identifier NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_date DATE DEFAULT SYSDATE NOT NULL,
    total NUMBER(7,2) NOT NULL,
    purchase_status CHAR(1) NOT NULL,
    supplier_identifier NUMBER NOT NULL
);

CREATE TABLE detailPurchase (
    identifier NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMBER NOT NULL,
    unit_price NUMBER(7,2) NOT NULL,
    subtotal NUMBER(9,2) NOT NULL,
    buys_identifier NUMBER NOT NULL,
    garment_identifier NUMBER NOT NULL
);

CREATE TABLE sale (
    identifier NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_date DATE DEFAULT SYSDATE NOT NULL,
    total NUMBER(7,2) NOT NULL,
    client_identifier NUMBER NOT NULL,
    employee_identifier NUMBER NOT NULL,
    sale_status CHAR(1) DEFAULT 'A' NOT NULL
);

CREATE TABLE detailSale (
    identifier NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_identifier NUMBER NOT NULL,
    garment_identifier NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    unit_price NUMBER(7,2) NOT NULL,
    subtotal NUMBER(9,2) GENERATED ALWAYS AS (quantity * unit_price) VIRTUAL
);

CREATE TABLE garment (
    identifier NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(60) NOT NULL,
    garment_size VARCHAR2(4) NOT NULL,
    color VARCHAR2(15) NOT NULL,
    unit_price NUMBER(7,2) NOT NULL,
    stock NUMBER NOT NULL,
    state CHAR(1) DEFAULT 'A' NOT NULL,
    register_date DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE supplier (
    identifier NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name VARCHAR2(100) NOT NULL,
    ruc CHAR(11) NOT NULL,
    phone CHAR(9) NOT NULL,
    address VARCHAR2(100) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    state CHAR(1) DEFAULT 'A' NOT NULL,
    register_date DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE employee (
    identifier NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(60) NOT NULL,
    dni CHAR(8) NOT NULL,
    phone CHAR(9) NOT NULL,
    email VARCHAR2(60)
);

CREATE TABLE customer (
    identifier NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(60) NOT NULL,
    dni CHAR(8) NOT NULL,
    phone CHAR(9) NOT NULL,
    address VARCHAR2(60) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    client_type CHAR(1) NOT NULL,
    state CHAR(1) NOT NULL
);



-- FOREIGN KEYS

ALTER TABLE buys
    ADD CONSTRAINT fk_buys_supplier
    FOREIGN KEY (supplier_identifier) REFERENCES supplier(identifier);

ALTER TABLE detailPurchase
    ADD CONSTRAINT fk_detailPurchase_buys
    FOREIGN KEY (buys_identifier) REFERENCES buys(identifier);

ALTER TABLE detailPurchase
    ADD CONSTRAINT fk_detailPurchase_garment
    FOREIGN KEY (garment_identifier) REFERENCES garment(identifier);

ALTER TABLE detailSale
    ADD CONSTRAINT fk_detailSale_garment
    FOREIGN KEY (product_identifier) REFERENCES garment(identifier);

ALTER TABLE detailSale
    ADD CONSTRAINT fk_detailSale_sale
    FOREIGN KEY (sale_identifier) REFERENCES sale(identifier);

ALTER TABLE sale
    ADD CONSTRAINT fk_sale_employee
    FOREIGN KEY (employee_identifier) REFERENCES employee(identifier);

ALTER TABLE sale
    ADD CONSTRAINT fk_sale_customer
    FOREIGN KEY (client_identifier) REFERENCES customer(identifier);



-- UNIQUE

ALTER TABLE supplier ADD CONSTRAINT uq_ruc_supplier UNIQUE (ruc);
ALTER TABLE supplier ADD CONSTRAINT uq_phone_supplier UNIQUE (phone);
ALTER TABLE supplier ADD CONSTRAINT uq_email_supplier UNIQUE (email);
ALTER TABLE employee ADD CONSTRAINT uq_employee_dni UNIQUE (dni);
ALTER TABLE customer ADD CONSTRAINT uq_customer_dni UNIQUE (dni);



-- CHECKS

ALTER TABLE supplier ADD CONSTRAINT chk_supplier_ruc CHECK (REGEXP_LIKE(ruc,'^\d{11}$'));
ALTER TABLE supplier ADD CONSTRAINT chk_phone CHECK (LENGTH(phone) = 9 AND SUBSTR(phone,1,1) = '9');
ALTER TABLE supplier ADD CONSTRAINT chk_supplier_mail CHECK (REGEXP_LIKE(email, '.+@.+\..+'));
ALTER TABLE employee ADD CONSTRAINT chk_employee_mail CHECK (email IS NULL OR REGEXP_LIKE(email, '.+@.+\..+'));
